parameters:
#    bdb_studios_auth.example.class: BDBStudios\AuthBundle\Example

services:
#    bdb_studios_auth.example:
#        class: %bdb_studios_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
